apiVersion: v1
kind: Pod
metadata:
  name: test-nfs
spec:
  containers:
  - name: test-nfs
    image: busybox
    command:
          - sh
          - -c
          - 'while true; do date > /mnt/nfs-verified; hostname >> /mnt/nfs-verified; sleep $(($RANDOM % 5 + 5)); done'
    volumeMounts:
      # name must match the volume name below
    - name: nfs-pvc
      mountPath: "/mnt"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: nfsclaim